### ISSUE TITLE
Using WIF token when testing

### ISSUE THREAD

**Issue by JvandeKraats** [firebase/firebase-functions-test#237]
### Version info

**firebase-functions-test:** v3.2.0

**firebase-functions:** v5.0.1

**firebase-admin:** v12.1.1

### Steps to reproduce

When running this part of the pipeline:  
``` yml
- name: Install functions dependencies
   run: ....

- name: Authenticate to Google Cloud
        id: GCloudAuth
        uses: google-github-actions/auth@v2.1.3
        with:
          project_id: xke-nxt-staging
          token_format: 'access_token'
          access_token_scopes: 'email, openid, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/firebase, https://www.googleapis.com/auth/datastore'
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_STAGING }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL_STAGING }}
          create_credentials_file: true

 - name: Setup service account key environment variable
    run: |
      echo "SERVICE_ACCOUNT_KEY=$(cat "${{ steps.GCloudAuth.outputs.credentials_file_path }}" | tr -d '\n')" >> $GITHUB_ENV

- name: Test functions
   run: npm run test:functions
````

I get an error while executing the tests.  
This is the error I'm getting: 
![image](https://github.com/firebase/firebase-functions-test/assets/7449547/62c45bb2-1441-4604-a961-f49b74b2665f)

### Expected behavior
I expected this test package to easily leverage the WIF token to authenticate and run the tests.

### Actual behavior
![image](https://github.com/firebase/firebase-functions-test/assets/7449547/f806432b-f2fd-4f86-9e2c-1df95bd8af99)

Has anyone else tried to get this working using WIF tokens?  
If you're missing info, please let me know.
